plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
}

// The code the phone and the browser share: the menus, the setup screen, the
// HUD and its dialogs, and the game's own controller (GameController), all in
// commonMain. The engine is the same C++ on both, reached through JNI on the
// phone and through the same JNI functions compiled to WebAssembly in the
// browser (NativeBridge, generated by tools/gen_native_bridge.py).
kotlin {
    android {
        namespace = "com.rm.scorchdroid.shared"
        compileSdk = 37
        minSdk = 26
    }
    wasmJs { browser() }

    sourceSets {
        commonMain.dependencies {
            api(libs.jb.compose.runtime)
            api(libs.jb.compose.foundation)
            api(libs.jb.compose.ui)
            api(libs.jb.compose.material3)
            api(libs.jb.compose.material.icons.extended)
            api(libs.kotlinx.coroutines.core)
        }
    }
}
