@file:Suppress("FunctionName")

// Generated by tools/gen_native_bridge.py from commonMain. Do not edit.

package com.rm.scorchdroid

private fun raw_nativeOnSurfaceCreated(env: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeOnSurfaceCreated(env, 0)")

private fun raw_nativeOnSurfaceChanged(env: Int, width: Int, height: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeOnSurfaceChanged(env, 0, width, height)")

private fun raw_nativeOnDrawFrame(env: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeOnDrawFrame(env, 0)")

private fun raw_nativeGetMissingPlateTexts(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeGetMissingPlateTexts(env, 0)")

private fun raw_nativeSetPlateText(env: Int, text: Int, width: Int, height: Int, pixels: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeSetPlateText(env, 0, text, width, height, pixels)")

private fun raw_nativePickTankPlate(env: Int, screenX: Float, screenY: Float): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativePickTankPlate(env, 0, screenX, screenY)")

private fun raw_nativeGetSoundLoops(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeGetSoundLoops(env, 0)")

private fun raw_nativeSetUiDensity(env: Int, density: Float): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeSetUiDensity(env, 0, density)")

private fun raw_nativePickTerrain(env: Int, screenX: Float, screenY: Float): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativePickTerrain(env, 0, screenX, screenY)")

private fun raw_nativeGetFrameStats(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeGetFrameStats(env, 0)")

private fun raw_nativeCameraDrag(env: Int, dx: Float, dy: Float): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeCameraDrag(env, 0, dx, dy)")

private fun raw_nativeCameraZoom(env: Int, scaleFactor: Float): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeCameraZoom(env, 0, scaleFactor)")

private fun raw_nativeCameraPan(env: Int, dx: Float, dy: Float): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeCameraPan(env, 0, dx, dy)")

private fun raw_nativeToggleCameraMode(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeToggleCameraMode(env, 0)")

private fun raw_nativeSetCameraPreset(env: Int, preset: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeSetCameraPreset(env, 0, preset)")

private fun raw_nativeMiniMapVersion(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeMiniMapVersion(env, 0)")

private fun raw_nativeMiniMapImage(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeMiniMapImage(env, 0)")

private fun raw_nativeCameraPlanInfo(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeCameraPlanInfo(env, 0)")

private fun raw_nativeCameraLookAt(env: Int, landscapeX: Float, landscapeY: Float): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeCameraLookAt(env, 0, landscapeX, landscapeY)")

private fun raw_nativeGetFloatingLabels(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_GameRenderer_nativeGetFloatingLabels(env, 0)")

actual object GameRenderer {
    actual fun nativeOnSurfaceCreated() {
        raw_nativeOnSurfaceCreated(Jni.env)
        Jni.release()
    }
    actual fun nativeOnSurfaceChanged(width: Int, height: Int) {
        raw_nativeOnSurfaceChanged(Jni.env, width, height)
        Jni.release()
    }
    actual fun nativeOnDrawFrame() {
        raw_nativeOnDrawFrame(Jni.env)
        Jni.release()
    }
    actual fun nativeGetMissingPlateTexts(): Array<String> {
        val result = Jni.readStrings(raw_nativeGetMissingPlateTexts(Jni.env))
        Jni.release()
        return result
    }
    actual fun nativeSetPlateText(text: String, width: Int, height: Int, pixels: IntArray) {
        raw_nativeSetPlateText(Jni.env, Jni.string(text), width, height, Jni.ints(pixels))
        Jni.release()
    }
    actual fun nativePickTankPlate(screenX: Float, screenY: Float): Int {
        val result = raw_nativePickTankPlate(Jni.env, screenX, screenY)
        Jni.release()
        return result
    }
    actual fun nativeGetSoundLoops(): Array<String> {
        val result = Jni.readStrings(raw_nativeGetSoundLoops(Jni.env))
        Jni.release()
        return result
    }
    actual fun nativeSetUiDensity(density: Float) {
        raw_nativeSetUiDensity(Jni.env, density)
        Jni.release()
    }
    actual fun nativePickTerrain(screenX: Float, screenY: Float): String {
        val result = Jni.readString(raw_nativePickTerrain(Jni.env, screenX, screenY))
        Jni.release()
        return result
    }
    actual fun nativeGetFrameStats(): String {
        val result = Jni.readString(raw_nativeGetFrameStats(Jni.env))
        Jni.release()
        return result
    }
    actual fun nativeCameraDrag(dx: Float, dy: Float) {
        raw_nativeCameraDrag(Jni.env, dx, dy)
        Jni.release()
    }
    actual fun nativeCameraZoom(scaleFactor: Float) {
        raw_nativeCameraZoom(Jni.env, scaleFactor)
        Jni.release()
    }
    actual fun nativeCameraPan(dx: Float, dy: Float) {
        raw_nativeCameraPan(Jni.env, dx, dy)
        Jni.release()
    }
    actual fun nativeToggleCameraMode(): Boolean {
        val result = (raw_nativeToggleCameraMode(Jni.env) != 0)
        Jni.release()
        return result
    }
    actual fun nativeSetCameraPreset(preset: Int) {
        raw_nativeSetCameraPreset(Jni.env, preset)
        Jni.release()
    }
    actual fun nativeMiniMapVersion(): Int {
        val result = raw_nativeMiniMapVersion(Jni.env)
        Jni.release()
        return result
    }
    actual fun nativeMiniMapImage(): IntArray {
        val result = Jni.readInts(raw_nativeMiniMapImage(Jni.env))
        Jni.release()
        return result
    }
    actual fun nativeCameraPlanInfo(): String {
        val result = Jni.readString(raw_nativeCameraPlanInfo(Jni.env))
        Jni.release()
        return result
    }
    actual fun nativeCameraLookAt(landscapeX: Float, landscapeY: Float) {
        raw_nativeCameraLookAt(Jni.env, landscapeX, landscapeY)
        Jni.release()
    }
    actual fun nativeGetFloatingLabels(): Array<String> {
        val result = Jni.readStrings(raw_nativeGetFloatingLabels(Jni.env))
        Jni.release()
        return result
    }
}
