@file:Suppress("FunctionName")

// Generated by tools/gen_native_bridge.py from commonMain. Do not edit.

package com.rm.scorchdroid

private fun raw_helloFromNative(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_helloFromNative(env, 0)")

private fun raw_initEngine(env: Int, dataRoot: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_initEngine(env, 0, dataRoot)")

private fun raw_startLocalGame(env: Int, overBluetooth: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_startLocalGame(env, 0, overBluetooth)")

private fun raw_tickEngine(env: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_tickEngine(env, 0)")

private fun raw_getGameStateDebugString(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getGameStateDebugString(env, 0)")

private fun raw_getMyTankId(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMyTankId(env, 0)")

private fun raw_fireWeapon(env: Int, playerId: Int, angleDegrees: Float, elevationDegrees: Float, power: Float): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_fireWeapon(env, 0, playerId, angleDegrees, elevationDegrees, power)")

private fun raw_pollSoundEvents(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_pollSoundEvents(env, 0)")

private fun raw_getMyMoney(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMyMoney(env, 0)")

private fun raw_getWeaponShop(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getWeaponShop(env, 0)")

private fun raw_buyAccessory(env: Int, accessoryId: Int, buy: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_buyAccessory(env, 0, accessoryId, buy)")

private fun raw_selectWeapon(env: Int, accessoryId: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_selectWeapon(env, 0, accessoryId)")

private fun raw_getCurrentWeaponName(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getCurrentWeaponName(env, 0)")

private fun raw_getMyStatusLabel(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMyStatusLabel(env, 0)")

private fun raw_isHostingOnNetwork(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_isHostingOnNetwork(env, 0)")

private fun raw_getServerPort(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getServerPort(env, 0)")

private fun raw_startJoinGame(env: Int, host: Int, port: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_startJoinGame(env, 0, host, port)")

private fun raw_startJoinGameBluetooth(env: Int, address: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_startJoinGameBluetooth(env, 0, address)")

private fun raw_getClientJoinState(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getClientJoinState(env, 0)")

private fun raw_getClientFailureReason(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getClientFailureReason(env, 0)")

private fun raw_useDefense(env: Int, accessoryId: Int, change: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_useDefense(env, 0, accessoryId, change)")

private fun raw_startLoadedGame(env: Int, name: Int, overBluetooth: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_startLoadedGame(env, 0, name, overBluetooth)")

private fun raw_deleteSavedGame(env: Int, name: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_deleteSavedGame(env, 0, name)")

private fun raw_listSavedGames(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_listSavedGames(env, 0)")

private fun raw_saveGame(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_saveGame(env, 0)")

private fun raw_getTankInfo(env: Int, playerId: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getTankInfo(env, 0, playerId)")

private fun raw_getGiftTargets(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getGiftTargets(env, 0)")

private fun raw_giftMoney(env: Int, toPlayerId: Int, amount: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_giftMoney(env, 0, toPlayerId, amount)")

private fun raw_getActiveDefenses(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getActiveDefenses(env, 0)")

private fun raw_getWindInfo(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getWindInfo(env, 0)")

private fun raw_submitMove(env: Int, moveType: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_submitMove(env, 0, moveType)")

private fun raw_aimAtPoint(env: Int, landscapeX: Float, landscapeY: Float): Float =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_aimAtPoint(env, 0, landscapeX, landscapeY)")

private fun raw_getMyMoveId(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMyMoveId(env, 0)")

private fun raw_getPhaseSecondsRemaining(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getPhaseSecondsRemaining(env, 0)")

private fun raw_getMyAim(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMyAim(env, 0)")

private fun raw_getPositionSelect(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getPositionSelect(env, 0)")

private fun raw_firePositionSelect(env: Int, landscapeX: Float, landscapeY: Float): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_firePositionSelect(env, 0, landscapeX, landscapeY)")

private fun raw_setAim(env: Int, angleDegrees: Float, elevationDegrees: Float, power: Float): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setAim(env, 0, angleDegrees, elevationDegrees, power)")

private fun raw_getPlayerList(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getPlayerList(env, 0)")

private fun raw_getRoundInfo(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getRoundInfo(env, 0)")

private fun raw_getMiniMapInfo(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMiniMapInfo(env, 0)")

private fun raw_getMiniMapTanks(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMiniMapTanks(env, 0)")

private fun raw_sendMapLine(env: Int, ax: Float, ay: Float, bx: Float, by: Float): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_sendMapLine(env, 0, ax, ay, bx, by)")

private fun raw_getMapLines(env: Int, afterId: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMapLines(env, 0, afterId)")

private fun raw_getMapLinesVersion(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getMapLinesVersion(env, 0)")

private fun raw_getScoreboardState(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getScoreboardState(env, 0)")

private fun raw_stopGame(env: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_stopGame(env, 0)")

private fun raw_getSetupOptions(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getSetupOptions(env, 0)")

private fun raw_setSetupOption(env: Int, name: Int, value: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setSetupOption(env, 0, name, value)")

private fun raw_resetSetupOptions(env: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_resetSetupOptions(env, 0)")

private fun raw_setPlayerName(env: Int, name: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setPlayerName(env, 0, name)")

private fun raw_setRenderOptions(env: Int, showTrees: Int, showFog: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setRenderOptions(env, 0, showTrees, showFog)")

private fun raw_setSightStyle(env: Int, style: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setSightStyle(env, 0, style)")

private fun raw_setCountdownSound(env: Int, on: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setCountdownSound(env, 0, on)")

private fun raw_setChatSound(env: Int, on: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setChatSound(env, 0, on)")

private fun raw_setTurnSound(env: Int, on: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setTurnSound(env, 0, on)")

private fun raw_setShowNamePlates(env: Int, show: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setShowNamePlates(env, 0, show)")

private fun raw_setShowHealthBars(env: Int, show: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setShowHealthBars(env, 0, show)")

private fun raw_setShowTankArrows(env: Int, show: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setShowTankArrows(env, 0, show)")

private fun raw_setTerrainDetail(env: Int, grid: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setTerrainDetail(env, 0, grid)")

private fun raw_setWaterDetail(env: Int, level: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setWaterDetail(env, 0, level)")

private fun raw_setEffectsDetail(env: Int, level: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setEffectsDetail(env, 0, level)")

private fun raw_setShadowDetail(env: Int, level: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setShadowDetail(env, 0, level)")

private fun raw_setReflectionStyle(env: Int, style: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setReflectionStyle(env, 0, style)")

private fun raw_getTerrainDetailRange(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getTerrainDetailRange(env, 0)")

private fun raw_getTankModels(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getTankModels(env, 0)")

private fun raw_getTankColors(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getTankColors(env, 0)")

private fun raw_getAvatars(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getAvatars(env, 0)")

private fun raw_setPlayerIdentity(env: Int, model: Int, colorIndex: Int, avatar: Int): Unit =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setPlayerIdentity(env, 0, model, colorIndex, avatar)")

private fun raw_loadSetupPreset(env: Int, path: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_loadSetupPreset(env, 0, path)")

private fun raw_getPresets(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getPresets(env, 0)")

private fun raw_getBots(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getBots(env, 0)")

private fun raw_getBotType(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getBotType(env, 0)")

private fun raw_setBotType(env: Int, name: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setBotType(env, 0, name)")

private fun raw_getBotTypes(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getBotTypes(env, 0)")

private fun raw_setBotTypes(env: Int, names: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setBotTypes(env, 0, names)")

private fun raw_getAmbientSounds(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getAmbientSounds(env, 0)")

private fun raw_getLandscapeTex(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getLandscapeTex(env, 0)")

private fun raw_getLandscapes(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getLandscapes(env, 0)")

private fun raw_getSelectedLandscapes(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getSelectedLandscapes(env, 0)")

private fun raw_setLandscapes(env: Int, names: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setLandscapes(env, 0, names)")

private fun raw_getAvailableMods(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getAvailableMods(env, 0)")

private fun raw_getSelectedMod(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getSelectedMod(env, 0)")

private fun raw_setSelectedMod(env: Int, name: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setSelectedMod(env, 0, name)")

private fun raw_sendChat(env: Int, channel: Int, text: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_sendChat(env, 0, channel, text)")

private fun raw_getChatLines(env: Int, afterId: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getChatLines(env, 0, afterId)")

private fun raw_getChatVersion(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getChatVersion(env, 0)")

private fun raw_setSimulationSpeed(env: Int, numerator: Int, denominator: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_setSimulationSpeed(env, 0, numerator, denominator)")

private fun raw_getSimulationSpeed(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getSimulationSpeed(env, 0)")

private fun raw_getAimSounds(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_getAimSounds(env, 0)")

private fun raw_hasAutoDefense(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_hasAutoDefense(env, 0)")

private fun raw_isGameHost(env: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_isGameHost(env, 0)")

private fun raw_adminCommand(env: Int, command: Int, playerId: Int, arg: Int): Int =
    js("globalThis.sd._Java_com_rm_scorchdroid_NativeBridge_adminCommand(env, 0, command, playerId, arg)")

actual object NativeBridge {
    actual fun helloFromNative(): String {
        val result = Jni.readString(raw_helloFromNative(Jni.env))
        Jni.release()
        return result
    }
    actual fun initEngine(dataRoot: String): Boolean {
        val result = (raw_initEngine(Jni.env, Jni.string(dataRoot)) != 0)
        Jni.release()
        return result
    }
    actual fun startLocalGame(overBluetooth: Boolean): Boolean {
        val result = (raw_startLocalGame(Jni.env, (if (overBluetooth) 1 else 0)) != 0)
        Jni.release()
        return result
    }
    actual fun tickEngine() {
        raw_tickEngine(Jni.env)
        Jni.release()
    }
    actual fun getGameStateDebugString(): String {
        val result = Jni.readString(raw_getGameStateDebugString(Jni.env))
        Jni.release()
        return result
    }
    actual fun getMyTankId(): Int {
        val result = raw_getMyTankId(Jni.env)
        Jni.release()
        return result
    }
    actual fun fireWeapon(playerId: Int, angleDegrees: Float, elevationDegrees: Float, power: Float): Boolean {
        val result = (raw_fireWeapon(Jni.env, playerId, angleDegrees, elevationDegrees, power) != 0)
        Jni.release()
        return result
    }
    actual fun pollSoundEvents(): Array<String> {
        val result = Jni.readStrings(raw_pollSoundEvents(Jni.env))
        Jni.release()
        return result
    }
    actual fun getMyMoney(): Int {
        val result = raw_getMyMoney(Jni.env)
        Jni.release()
        return result
    }
    actual fun getWeaponShop(): Array<String> {
        val result = Jni.readStrings(raw_getWeaponShop(Jni.env))
        Jni.release()
        return result
    }
    actual fun buyAccessory(accessoryId: Int, buy: Boolean): Boolean {
        val result = (raw_buyAccessory(Jni.env, accessoryId, (if (buy) 1 else 0)) != 0)
        Jni.release()
        return result
    }
    actual fun selectWeapon(accessoryId: Int): Boolean {
        val result = (raw_selectWeapon(Jni.env, accessoryId) != 0)
        Jni.release()
        return result
    }
    actual fun getCurrentWeaponName(): String {
        val result = Jni.readString(raw_getCurrentWeaponName(Jni.env))
        Jni.release()
        return result
    }
    actual fun getMyStatusLabel(): String {
        val result = Jni.readString(raw_getMyStatusLabel(Jni.env))
        Jni.release()
        return result
    }
    actual fun isHostingOnNetwork(): Boolean {
        val result = (raw_isHostingOnNetwork(Jni.env) != 0)
        Jni.release()
        return result
    }
    actual fun getServerPort(): Int {
        val result = raw_getServerPort(Jni.env)
        Jni.release()
        return result
    }
    actual fun startJoinGame(host: String, port: Int): Boolean {
        val result = (raw_startJoinGame(Jni.env, Jni.string(host), port) != 0)
        Jni.release()
        return result
    }
    actual fun startJoinGameBluetooth(address: String): Boolean {
        val result = (raw_startJoinGameBluetooth(Jni.env, Jni.string(address)) != 0)
        Jni.release()
        return result
    }
    actual fun getClientJoinState(): Int {
        val result = raw_getClientJoinState(Jni.env)
        Jni.release()
        return result
    }
    actual fun getClientFailureReason(): String {
        val result = Jni.readString(raw_getClientFailureReason(Jni.env))
        Jni.release()
        return result
    }
    actual fun useDefense(accessoryId: Int, change: Int): Boolean {
        val result = (raw_useDefense(Jni.env, accessoryId, change) != 0)
        Jni.release()
        return result
    }
    actual fun startLoadedGame(name: String, overBluetooth: Boolean): Boolean {
        val result = (raw_startLoadedGame(Jni.env, Jni.string(name), (if (overBluetooth) 1 else 0)) != 0)
        Jni.release()
        return result
    }
    actual fun deleteSavedGame(name: String): Boolean {
        val result = (raw_deleteSavedGame(Jni.env, Jni.string(name)) != 0)
        Jni.release()
        return result
    }
    actual fun listSavedGames(): Array<String> {
        val result = Jni.readStrings(raw_listSavedGames(Jni.env))
        Jni.release()
        return result
    }
    actual fun saveGame(): String {
        val result = Jni.readString(raw_saveGame(Jni.env))
        Jni.release()
        return result
    }
    actual fun getTankInfo(playerId: Int): String {
        val result = Jni.readString(raw_getTankInfo(Jni.env, playerId))
        Jni.release()
        return result
    }
    actual fun getGiftTargets(): Array<String> {
        val result = Jni.readStrings(raw_getGiftTargets(Jni.env))
        Jni.release()
        return result
    }
    actual fun giftMoney(toPlayerId: Int, amount: Int): Boolean {
        val result = (raw_giftMoney(Jni.env, toPlayerId, amount) != 0)
        Jni.release()
        return result
    }
    actual fun getActiveDefenses(): String {
        val result = Jni.readString(raw_getActiveDefenses(Jni.env))
        Jni.release()
        return result
    }
    actual fun getWindInfo(): String {
        val result = Jni.readString(raw_getWindInfo(Jni.env))
        Jni.release()
        return result
    }
    actual fun submitMove(moveType: Int): Boolean {
        val result = (raw_submitMove(Jni.env, moveType) != 0)
        Jni.release()
        return result
    }
    actual fun aimAtPoint(landscapeX: Float, landscapeY: Float): Float {
        val result = raw_aimAtPoint(Jni.env, landscapeX, landscapeY)
        Jni.release()
        return result
    }
    actual fun getMyMoveId(): Int {
        val result = raw_getMyMoveId(Jni.env)
        Jni.release()
        return result
    }
    actual fun getPhaseSecondsRemaining(): Int {
        val result = raw_getPhaseSecondsRemaining(Jni.env)
        Jni.release()
        return result
    }
    actual fun getMyAim(): String {
        val result = Jni.readString(raw_getMyAim(Jni.env))
        Jni.release()
        return result
    }
    actual fun getPositionSelect(): String {
        val result = Jni.readString(raw_getPositionSelect(Jni.env))
        Jni.release()
        return result
    }
    actual fun firePositionSelect(landscapeX: Float, landscapeY: Float): Boolean {
        val result = (raw_firePositionSelect(Jni.env, landscapeX, landscapeY) != 0)
        Jni.release()
        return result
    }
    actual fun setAim(angleDegrees: Float, elevationDegrees: Float, power: Float): Boolean {
        val result = (raw_setAim(Jni.env, angleDegrees, elevationDegrees, power) != 0)
        Jni.release()
        return result
    }
    actual fun getPlayerList(): Array<String> {
        val result = Jni.readStrings(raw_getPlayerList(Jni.env))
        Jni.release()
        return result
    }
    actual fun getRoundInfo(): String {
        val result = Jni.readString(raw_getRoundInfo(Jni.env))
        Jni.release()
        return result
    }
    actual fun getMiniMapInfo(): String {
        val result = Jni.readString(raw_getMiniMapInfo(Jni.env))
        Jni.release()
        return result
    }
    actual fun getMiniMapTanks(): Array<String> {
        val result = Jni.readStrings(raw_getMiniMapTanks(Jni.env))
        Jni.release()
        return result
    }
    actual fun sendMapLine(ax: Float, ay: Float, bx: Float, by: Float): Boolean {
        val result = (raw_sendMapLine(Jni.env, ax, ay, bx, by) != 0)
        Jni.release()
        return result
    }
    actual fun getMapLines(afterId: Int): Array<String> {
        val result = Jni.readStrings(raw_getMapLines(Jni.env, afterId))
        Jni.release()
        return result
    }
    actual fun getMapLinesVersion(): Int {
        val result = raw_getMapLinesVersion(Jni.env)
        Jni.release()
        return result
    }
    actual fun getScoreboardState(): Int {
        val result = raw_getScoreboardState(Jni.env)
        Jni.release()
        return result
    }
    actual fun stopGame() {
        raw_stopGame(Jni.env)
        Jni.release()
    }
    actual fun getSetupOptions(): Array<String> {
        val result = Jni.readStrings(raw_getSetupOptions(Jni.env))
        Jni.release()
        return result
    }
    actual fun setSetupOption(name: String, value: String): Boolean {
        val result = (raw_setSetupOption(Jni.env, Jni.string(name), Jni.string(value)) != 0)
        Jni.release()
        return result
    }
    actual fun resetSetupOptions() {
        raw_resetSetupOptions(Jni.env)
        Jni.release()
    }
    actual fun setPlayerName(name: String): String {
        val result = Jni.readString(raw_setPlayerName(Jni.env, Jni.string(name)))
        Jni.release()
        return result
    }
    actual fun setRenderOptions(showTrees: Boolean, showFog: Boolean) {
        raw_setRenderOptions(Jni.env, (if (showTrees) 1 else 0), (if (showFog) 1 else 0))
        Jni.release()
    }
    actual fun setSightStyle(style: Int) {
        raw_setSightStyle(Jni.env, style)
        Jni.release()
    }
    actual fun setCountdownSound(on: Boolean) {
        raw_setCountdownSound(Jni.env, (if (on) 1 else 0))
        Jni.release()
    }
    actual fun setChatSound(on: Boolean) {
        raw_setChatSound(Jni.env, (if (on) 1 else 0))
        Jni.release()
    }
    actual fun setTurnSound(on: Boolean) {
        raw_setTurnSound(Jni.env, (if (on) 1 else 0))
        Jni.release()
    }
    actual fun setShowNamePlates(show: Boolean) {
        raw_setShowNamePlates(Jni.env, (if (show) 1 else 0))
        Jni.release()
    }
    actual fun setShowHealthBars(show: Boolean) {
        raw_setShowHealthBars(Jni.env, (if (show) 1 else 0))
        Jni.release()
    }
    actual fun setShowTankArrows(show: Boolean) {
        raw_setShowTankArrows(Jni.env, (if (show) 1 else 0))
        Jni.release()
    }
    actual fun setTerrainDetail(grid: Int) {
        raw_setTerrainDetail(Jni.env, grid)
        Jni.release()
    }
    actual fun setWaterDetail(level: Int) {
        raw_setWaterDetail(Jni.env, level)
        Jni.release()
    }
    actual fun setEffectsDetail(level: Int) {
        raw_setEffectsDetail(Jni.env, level)
        Jni.release()
    }
    actual fun setShadowDetail(level: Int) {
        raw_setShadowDetail(Jni.env, level)
        Jni.release()
    }
    actual fun setReflectionStyle(style: Int) {
        raw_setReflectionStyle(Jni.env, style)
        Jni.release()
    }
    actual fun getTerrainDetailRange(): String {
        val result = Jni.readString(raw_getTerrainDetailRange(Jni.env))
        Jni.release()
        return result
    }
    actual fun getTankModels(): Array<String> {
        val result = Jni.readStrings(raw_getTankModels(Jni.env))
        Jni.release()
        return result
    }
    actual fun getTankColors(): IntArray {
        val result = Jni.readInts(raw_getTankColors(Jni.env))
        Jni.release()
        return result
    }
    actual fun getAvatars(): Array<String> {
        val result = Jni.readStrings(raw_getAvatars(Jni.env))
        Jni.release()
        return result
    }
    actual fun setPlayerIdentity(model: String, colorIndex: Int, avatar: String) {
        raw_setPlayerIdentity(Jni.env, Jni.string(model), colorIndex, Jni.string(avatar))
        Jni.release()
    }
    actual fun loadSetupPreset(path: String): Boolean {
        val result = (raw_loadSetupPreset(Jni.env, Jni.string(path)) != 0)
        Jni.release()
        return result
    }
    actual fun getPresets(): Array<String> {
        val result = Jni.readStrings(raw_getPresets(Jni.env))
        Jni.release()
        return result
    }
    actual fun getBots(): Array<String> {
        val result = Jni.readStrings(raw_getBots(Jni.env))
        Jni.release()
        return result
    }
    actual fun getBotType(): String {
        val result = Jni.readString(raw_getBotType(Jni.env))
        Jni.release()
        return result
    }
    actual fun setBotType(name: String): Boolean {
        val result = (raw_setBotType(Jni.env, Jni.string(name)) != 0)
        Jni.release()
        return result
    }
    actual fun getBotTypes(): Array<String> {
        val result = Jni.readStrings(raw_getBotTypes(Jni.env))
        Jni.release()
        return result
    }
    actual fun setBotTypes(names: Array<String>): Boolean {
        val result = (raw_setBotTypes(Jni.env, Jni.strings(names)) != 0)
        Jni.release()
        return result
    }
    actual fun getAmbientSounds(): Array<String> {
        val result = Jni.readStrings(raw_getAmbientSounds(Jni.env))
        Jni.release()
        return result
    }
    actual fun getLandscapeTex(): String {
        val result = Jni.readString(raw_getLandscapeTex(Jni.env))
        Jni.release()
        return result
    }
    actual fun getLandscapes(): Array<String> {
        val result = Jni.readStrings(raw_getLandscapes(Jni.env))
        Jni.release()
        return result
    }
    actual fun getSelectedLandscapes(): Array<String> {
        val result = Jni.readStrings(raw_getSelectedLandscapes(Jni.env))
        Jni.release()
        return result
    }
    actual fun setLandscapes(names: Array<String>): Boolean {
        val result = (raw_setLandscapes(Jni.env, Jni.strings(names)) != 0)
        Jni.release()
        return result
    }
    actual fun getAvailableMods(): Array<String> {
        val result = Jni.readStrings(raw_getAvailableMods(Jni.env))
        Jni.release()
        return result
    }
    actual fun getSelectedMod(): String {
        val result = Jni.readString(raw_getSelectedMod(Jni.env))
        Jni.release()
        return result
    }
    actual fun setSelectedMod(name: String): Boolean {
        val result = (raw_setSelectedMod(Jni.env, Jni.string(name)) != 0)
        Jni.release()
        return result
    }
    actual fun sendChat(channel: String, text: String): Boolean {
        val result = (raw_sendChat(Jni.env, Jni.string(channel), Jni.string(text)) != 0)
        Jni.release()
        return result
    }
    actual fun getChatLines(afterId: Int): Array<String> {
        val result = Jni.readStrings(raw_getChatLines(Jni.env, afterId))
        Jni.release()
        return result
    }
    actual fun getChatVersion(): Int {
        val result = raw_getChatVersion(Jni.env)
        Jni.release()
        return result
    }
    actual fun setSimulationSpeed(numerator: Int, denominator: Int): Boolean {
        val result = (raw_setSimulationSpeed(Jni.env, numerator, denominator) != 0)
        Jni.release()
        return result
    }
    actual fun getSimulationSpeed(): String {
        val result = Jni.readString(raw_getSimulationSpeed(Jni.env))
        Jni.release()
        return result
    }
    actual fun getAimSounds(): String {
        val result = Jni.readString(raw_getAimSounds(Jni.env))
        Jni.release()
        return result
    }
    actual fun hasAutoDefense(): Boolean {
        val result = (raw_hasAutoDefense(Jni.env) != 0)
        Jni.release()
        return result
    }
    actual fun isGameHost(): Boolean {
        val result = (raw_isGameHost(Jni.env) != 0)
        Jni.release()
        return result
    }
    actual fun adminCommand(command: Int, playerId: Int, arg: String): Boolean {
        val result = (raw_adminCommand(Jni.env, command, playerId, Jni.string(arg)) != 0)
        Jni.release()
        return result
    }
}
