#!/usr/bin/env python3
"""Generates both halves of the engine's calls from one list.

The lists are NativeBridge and GameRenderer in shared/src/commonMain
(`expect object`, one `fun` per call). The C++ behind each call is
Java_com_rm_scorchdroid_<Object>_<name> in engine_jni.cpp or renderer_jni.cpp.
This writes each platform's side, which is never edited by hand:

- androidMain: `actual external fun`, i.e. JNI.
- wasmJsMain: the same JNI functions, compiled to WebAssembly against
  web/engine/include/jni.h and called through the page's engine module
  (globalThis.sd), with strings and arrays passed as JNI objects (Jni.kt).

Run after changing a list:   python3 tools/gen_native_bridge.py
Check it is in step:         python3 tools/gen_native_bridge.py --check
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = "shared/src/{}/kotlin/com/rm/scorchdroid"
OBJECTS = ["NativeBridge", "GameRenderer"]
LIBRARY = "scorchdroid_engine"

# How each Kotlin type crosses into the WebAssembly JNI function, and how its
# result comes back.
RAW_TYPE = {
    "String": "Int", "Array<String>": "Int", "IntArray": "Int",
    "Boolean": "Int", "Int": "Int", "Float": "Float", "Unit": "Unit",
}
ARG_IN = {
    "String": "Jni.string({})",
    "Array<String>": "Jni.strings({})",
    "IntArray": "Jni.ints({})",
    "Boolean": "(if ({}) 1 else 0)",
    "Int": "{}",
    "Float": "{}",
}
RESULT_OUT = {
    "String": "Jni.readString({})",
    "Array<String>": "Jni.readStrings({})",
    "IntArray": "Jni.readInts({})",
    "Boolean": "({} != 0)",
    "Int": "{}",
    "Float": "{}",
}


def parse(name):
    text = (ROOT / PKG.format("commonMain") / f"{name}.kt").read_text()
    start = text.index(f"expect object {name} {{")
    body = text[start:]
    # The object ends at the first line that is a bare closing brace.
    body = body[: body.index("\n}\n")]
    # Drop comments, then join each declaration onto one line.
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    calls = []
    for m in re.finditer(r"\bfun\s+(\w+)\s*\(([^)]*)\)\s*(?::\s*([\w<>]+))?", body):
        fname, params, ret = m.group(1), m.group(2), m.group(3) or "Unit"
        args = []
        for p in [x.strip() for x in params.split(",") if x.strip()]:
            pname, ptype = [x.strip() for x in p.split(":")]
            if ptype not in ARG_IN:
                sys.exit(f"{name}.{fname}: no mapping for parameter type {ptype}")
            args.append((pname, ptype))
        if ret not in RAW_TYPE:
            sys.exit(f"{name}.{fname}: no mapping for return type {ret}")
        calls.append((fname, args, ret))
    return calls


def signature(args, ret):
    params = ", ".join(f"{n}: {t}" for n, t in args)
    return f"({params})" + ("" if ret == "Unit" else f": {ret}")


def android(name, calls):
    out = [
        "// Generated by tools/gen_native_bridge.py from commonMain. Do not edit.",
        "",
        "package com.rm.scorchdroid",
        "",
        f"actual object {name} {{",
        "    init {",
        f"        System.loadLibrary(\"{LIBRARY}\")",
        "    }",
        "",
    ]
    for fname, args, ret in calls:
        out.append(f"    actual external fun {fname}{signature(args, ret)}")
    out.append("}")
    return "\n".join(out) + "\n"


def wasm(name, calls):
    symbol = f"_Java_com_rm_scorchdroid_{name}_"
    out = [
        '@file:Suppress("FunctionName")',
        "",
        "// Generated by tools/gen_native_bridge.py from commonMain. Do not edit.",
        "",
        "package com.rm.scorchdroid",
        "",
    ]
    for fname, args, ret in calls:
        raw_params = ", ".join(["env: Int"] + [f"{n}: {RAW_TYPE[t]}" for n, t in args])
        call_args = ", ".join(["env", "0"] + [n for n, _ in args])
        out.append(f"private fun raw_{fname}({raw_params}): {RAW_TYPE[ret]} =")
        out.append(f"    js(\"globalThis.sd.{symbol}{fname}({call_args})\")")
        out.append("")
    out.append(f"actual object {name} {{")
    for fname, args, ret in calls:
        passed = ", ".join(["Jni.env"] + [ARG_IN[t].format(n) for n, t in args])
        out.append(f"    actual fun {fname}{signature(args, ret)} {{")
        if ret == "Unit":
            out.append(f"        raw_{fname}({passed})")
            out.append("        Jni.release()")
        else:
            out.append(f"        val result = {RESULT_OUT[ret].format(f'raw_{fname}({passed})')}")
            out.append("        Jni.release()")
            out.append("        return result")
        out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv
    stale = []
    for name in OBJECTS:
        calls = parse(name)
        targets = {
            ROOT / PKG.format("androidMain") / f"{name}.android.kt": android(name, calls),
            ROOT / PKG.format("wasmJsMain") / f"{name}.wasmJs.kt": wasm(name, calls),
        }
        for path, text in targets.items():
            if check:
                if not path.exists() or path.read_text() != text:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
    if stale:
        sys.exit("Out of step with commonMain, run tools/gen_native_bridge.py:\n  " + "\n  ".join(stale))


if __name__ == "__main__":
    main()
