// Generated by tools/gen_native_bridge.py from commonMain. Do not edit.

package com.rm.scorchdroid

actual object GameRenderer {
    init {
        System.loadLibrary("scorchdroid_engine")
    }

    actual external fun nativeOnSurfaceCreated()
    actual external fun nativeOnSurfaceChanged(width: Int, height: Int)
    actual external fun nativeOnDrawFrame()
    actual external fun nativeGetMissingPlateTexts(): Array<String>
    actual external fun nativeSetPlateText(text: String, width: Int, height: Int, pixels: IntArray)
    actual external fun nativePickTankPlate(screenX: Float, screenY: Float): Int
    actual external fun nativeGetSoundLoops(): Array<String>
    actual external fun nativeSetUiDensity(density: Float)
    actual external fun nativePickTerrain(screenX: Float, screenY: Float): String
    actual external fun nativeGetFrameStats(): String
    actual external fun nativeCameraDrag(dx: Float, dy: Float)
    actual external fun nativeCameraZoom(scaleFactor: Float)
    actual external fun nativeCameraPan(dx: Float, dy: Float)
    actual external fun nativeToggleCameraMode(): Boolean
    actual external fun nativeSetCameraPreset(preset: Int)
    actual external fun nativeMiniMapVersion(): Int
    actual external fun nativeMiniMapImage(): IntArray
    actual external fun nativeCameraPlanInfo(): String
    actual external fun nativeCameraLookAt(landscapeX: Float, landscapeY: Float)
    actual external fun nativeGetFloatingLabels(): Array<String>
}
