// Generated by tools/gen_native_bridge.py from commonMain. Do not edit.

package com.rm.scorchdroid

actual object NativeBridge {
    init {
        System.loadLibrary("scorchdroid_engine")
    }

    actual external fun helloFromNative(): String
    actual external fun initEngine(dataRoot: String): Boolean
    actual external fun startLocalGame(overBluetooth: Boolean): Boolean
    actual external fun tickEngine()
    actual external fun getGameStateDebugString(): String
    actual external fun getMyTankId(): Int
    actual external fun fireWeapon(playerId: Int, angleDegrees: Float, elevationDegrees: Float, power: Float): Boolean
    actual external fun pollSoundEvents(): Array<String>
    actual external fun getMyMoney(): Int
    actual external fun getWeaponShop(): Array<String>
    actual external fun buyAccessory(accessoryId: Int, buy: Boolean): Boolean
    actual external fun selectWeapon(accessoryId: Int): Boolean
    actual external fun getCurrentWeaponName(): String
    actual external fun getMyStatusLabel(): String
    actual external fun isHostingOnNetwork(): Boolean
    actual external fun getServerPort(): Int
    actual external fun startJoinGame(host: String, port: Int): Boolean
    actual external fun startJoinGameBluetooth(address: String): Boolean
    actual external fun getClientJoinState(): Int
    actual external fun getClientFailureReason(): String
    actual external fun useDefense(accessoryId: Int, change: Int): Boolean
    actual external fun startLoadedGame(name: String, overBluetooth: Boolean): Boolean
    actual external fun deleteSavedGame(name: String): Boolean
    actual external fun listSavedGames(): Array<String>
    actual external fun saveGame(): String
    actual external fun getTankInfo(playerId: Int): String
    actual external fun getGiftTargets(): Array<String>
    actual external fun giftMoney(toPlayerId: Int, amount: Int): Boolean
    actual external fun getActiveDefenses(): String
    actual external fun getWindInfo(): String
    actual external fun submitMove(moveType: Int): Boolean
    actual external fun aimAtPoint(landscapeX: Float, landscapeY: Float): Float
    actual external fun getMyMoveId(): Int
    actual external fun getPhaseSecondsRemaining(): Int
    actual external fun getMyAim(): String
    actual external fun getPositionSelect(): String
    actual external fun firePositionSelect(landscapeX: Float, landscapeY: Float): Boolean
    actual external fun setAim(angleDegrees: Float, elevationDegrees: Float, power: Float): Boolean
    actual external fun getPlayerList(): Array<String>
    actual external fun getRoundInfo(): String
    actual external fun getMiniMapInfo(): String
    actual external fun getMiniMapTanks(): Array<String>
    actual external fun sendMapLine(ax: Float, ay: Float, bx: Float, by: Float): Boolean
    actual external fun getMapLines(afterId: Int): Array<String>
    actual external fun getMapLinesVersion(): Int
    actual external fun getScoreboardState(): Int
    actual external fun stopGame()
    actual external fun getSetupOptions(): Array<String>
    actual external fun setSetupOption(name: String, value: String): Boolean
    actual external fun resetSetupOptions()
    actual external fun setPlayerName(name: String): String
    actual external fun setRenderOptions(showTrees: Boolean, showFog: Boolean)
    actual external fun setSightStyle(style: Int)
    actual external fun setCountdownSound(on: Boolean)
    actual external fun setChatSound(on: Boolean)
    actual external fun setTurnSound(on: Boolean)
    actual external fun setShowNamePlates(show: Boolean)
    actual external fun setShowHealthBars(show: Boolean)
    actual external fun setShowTankArrows(show: Boolean)
    actual external fun setTerrainDetail(grid: Int)
    actual external fun setWaterDetail(level: Int)
    actual external fun setEffectsDetail(level: Int)
    actual external fun setShadowDetail(level: Int)
    actual external fun setReflectionStyle(style: Int)
    actual external fun getTerrainDetailRange(): String
    actual external fun getTankModels(): Array<String>
    actual external fun getTankColors(): IntArray
    actual external fun getAvatars(): Array<String>
    actual external fun setPlayerIdentity(model: String, colorIndex: Int, avatar: String)
    actual external fun loadSetupPreset(path: String): Boolean
    actual external fun getPresets(): Array<String>
    actual external fun getBots(): Array<String>
    actual external fun getBotType(): String
    actual external fun setBotType(name: String): Boolean
    actual external fun getBotTypes(): Array<String>
    actual external fun setBotTypes(names: Array<String>): Boolean
    actual external fun getAmbientSounds(): Array<String>
    actual external fun getLandscapeTex(): String
    actual external fun getLandscapes(): Array<String>
    actual external fun getSelectedLandscapes(): Array<String>
    actual external fun setLandscapes(names: Array<String>): Boolean
    actual external fun getAvailableMods(): Array<String>
    actual external fun getSelectedMod(): String
    actual external fun setSelectedMod(name: String): Boolean
    actual external fun sendChat(channel: String, text: String): Boolean
    actual external fun getChatLines(afterId: Int): Array<String>
    actual external fun getChatVersion(): Int
    actual external fun setSimulationSpeed(numerator: Int, denominator: Int): Boolean
    actual external fun getSimulationSpeed(): String
    actual external fun getAimSounds(): String
    actual external fun hasAutoDefense(): Boolean
    actual external fun isGameHost(): Boolean
    actual external fun adminCommand(command: Int, playerId: Int, arg: String): Boolean
}
